### ISSUE TITLE
Error with IP INTEGRATOR

### ISSUE THREAD

**Issue by qarlosalberto** [barbedo/vivado-git#2]
I have this error with I create a project with IP INTEGRATOR:

```
ERROR: [Vivado-projutils-19] This design contains BD sources. The option -no_copy_sources cannot be used without -use_bd_files. Please remove -no_copy_sources if you wish to write out BD's as procs in the project tcl, otherwise add the option -use_bd_files to directly include the *.bd files to the new project 
ERROR: [Common 17-39] 'send_msg_id' failed due to earlier errors.
```

**Comment by barbedo** [comment]
Hi there.

I never tested the modified `write_project_tcl.tcl` script with BD files. Sorry for that.

I'll check how to work around this issue later this week.

**Comment by qarlosalberto** [comment]
Thank you!!

I have other problem. When I run ```git commit```, It creates the .tcl script, but Vivado doesnt close this window:

![captura de pantalla_2018-01-31_12-36-02](https://user-images.githubusercontent.com/5955143/35621080-667256d0-0683-11e8-87d6-17e630476362.png)

**Comment by qarlosalberto** [comment]
I must kill the Vivado process and re-run it.

**Comment by barbedo** [comment]
In the meantime, could you try to add `-use_bd_files` as an option of `write_project_tcl_git` on the lines 56 and 79 of the `git_wrapper.tcl` file?

**Comment by qarlosalberto** [comment]
I have to do more tests, but it seems to work. :)

>  In the meantime, could you try to add -use_bd_files as an option of write_project_tcl_git on the lines 56 and 79 of the git_wrapper.tcl file?
