### ISSUE TITLE
excisting vivado projects

### ISSUE THREAD

**Issue by el3ctrician** [barbedo/vivado-git#4]
Hello,
is there is a way to use the scripts with existing vivado projects in order to migrate them to git ? some sort of copying sources and organizing everything to create it ?

Thanks

**Comment by barbedo** [comment]
Hey,

I don't have a script that does exactly that, sorry.

But you can try to do something like the following:
1. Move everything under `project_name.srcs` (and `*.sdk` or whatever you want to track) to outside of the default Vivado project tree (e.g. `mv top_dir/project_name/project_name.srcs/* top_dir/srcs/`)
2. Rename the project folder to `vivado_project` (e.g. `top_dir/project_name/project_name.*` to `top_dir/vivado_project/project_name.*`).
3. Open Vivado and re-add the sources to the project without copying them.
4. Run `wproj` to generate the Tcl project script, copy everything minus the `vivado_project` folder to another folder and try to source the project script from there. This way you can check if it's correctly regenerating the project.

Tell me if you have any trouble. I may try to add a converter one day.
